language: android
sudo: false

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-24.0.2
    - android-24

script:
  - chmod +x ./gradlew
  - ./gradlew build connectedCheck --debug
